version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - '3000:3000'

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
