version: '3.8'
services:
  api:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: node api/index.js
    ports:
      - '3000:3000'

  bot:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: node bot/index.js
